name: albrog_mobile_app
description: "تطبيق البروج العقاري - Albrog Real Estate App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # iOS icons
  cupertino_icons: ^1.0.6

  # UI & Design
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  photo_view: ^0.14.0
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.1.0
  youtube_player_flutter: ^8.1.0 # Or the latest stable version

  # Navigation & State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Network & API
  http: ^1.1.2
  dio: ^5.4.0
  connectivity_plus: ^5.0.2

  # Maps & Location
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  video_player: ^2.8.1 # تأكد من استخدام أحدث إصدار مستقر
  chewie: ^1.7.4      # ⬅️ أضف هذا
  # Communication
  url_launcher: ^6.2.2
  share_plus: ^7.2.2

  # Local Storage
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2

  # Utilities
  intl: ^0.20.2
  timeago: ^3.6.1
  flutter_rating_bar: ^4.0.1
  percent_indicator: ^4.2.3

  # Arabic/RTL Support
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600

dependency_overrides:
  flutter_inappwebview: ^6.1.5
  youtube_player_flutter: ^9.1.1

# ✅ إعدادات أيقونة التطبيق
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#FFFFFF"
    theme_color: "#2196F3"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"
